import { useState } from 'react';
import { EmptyState, ErrorState, LoadingState } from '../../components/AsyncState';
import { useConversations, useTakeOverConversation } from '../../features/conversations/api';
import './ConversationsPage.css';

export default function ConversationsPage() {
  const [status, setStatus] = useState(''); const conversations = useConversations(status); const takeOver = useTakeOverConversation();
  return <div><div className="page-header"><div><h1 className="page-title">Conversas</h1><p className="page-subtitle">Atualizado automaticamente a cada 15 segundos.</p></div><select className="input-field compact-field" value={status} onChange={(event) => setStatus(event.target.value)} aria-label="Filtrar conversas"><option value="">Todas</option><option value="BOT_ACTIVE">Bot ativo</option><option value="TRANSFERRED">Transferidas</option><option value="COMPLETED">Concluídas</option></select></div>{conversations.isLoading ? <LoadingState /> : conversations.isError ? <ErrorState onRetry={() => conversations.refetch()} /> : conversations.data?.content.length ? <div className="conversations-list">{conversations.data.content.map((conversation) => <article className="conversation-item glass-card" key={conversation.id}><div className="conversation-avatar">{(conversation.patientName ?? conversation.phone).slice(0, 1)}</div><div className="conversation-body"><strong>{conversation.patientName ?? conversation.phone}</strong><p>{conversation.lastMessage}</p><small>{new Date(conversation.updatedAt).toLocaleString('pt-BR')}</small></div><div><span className={`badge ${conversation.status === 'COMPLETED' ? 'badge-success' : conversation.status === 'TRANSFERRED' ? 'badge-warning' : 'badge-info'}`}>{conversation.status}</span>{conversation.status === 'TRANSFERRED' && !conversation.takenOverByCurrentUser && <button className="btn btn-primary btn-sm" disabled={takeOver.isPending} onClick={() => takeOver.mutate(conversation.id)}>Assumir</button>}</div></article>)}</div> : <EmptyState title="Nenhuma conversa encontrada" description="As conversas do WhatsApp aparecerão aqui." />}</div>;
}
